### ISSUE TITLE
Incompatibility with Zenith (com.muirey03.zenith)

### ISSUE THREAD

**Issue by StarGazer1258** [ConorTheDev/Pastel#1]
**Device:** iPhone 8 A1864  
**iOS Version:** 13.2.3  
**Jailbreak:** checkra1n v0.9.6 beta  
  
**Description of bug:**
With Zenith (com.muirey03.zenith) installed, opening a stack removes the badge color of the top app. Opening an app and returning to the home screen resets the badge color.  
  
See https://www.youtube.com/watch?v=8vHDFhdsVcE  
  
**Steps to reproduce:**  
1. Install Pastel and Zenith
2. Stack two or more apps with notification badges
3. Open the stack
3. Open any app and return to home screen to reset badge colors
  
**Expected behavior:** All apps in the stack have colored badges.  
**Actual behavior:** Only sub-apps in stack have colored badges.

**Comment by ConorTheDev** [comment]
Thanks for the report. Will contact Muirey about this and see how to add compatibility :)

**Comment by ConorTheDev** [comment]
Hey, sorry about the delay. Since I do not have a copy of Zenith, can you try [this build](https://github.com/ConorTheDev/Pastel/releases/download/BETA1/me.conorthedev.pastel_1.0-62+debug_iphoneos-arm.deb) and see does it work?

Thanks in advance!

**Comment by ConorTheDev** [comment]
This was fixed in ba43950b8b8ff0953cad774607a4f61436a6f268, thanks for submitting a bug report! This feature will be available publicly in v1.1!
