### ISSUE TITLE
Badge color reset

### ISSUE THREAD

**Issue by swing7wing** [ConorTheDev/Pastel#4]
Just noticed a random bug after the 1.1 update. One of my apps had a red badge color, even though the app icon is almost completely black. After opening the app, the problem went away and the badge color was corrected. ![image](https://user-images.githubusercontent.com/14091307/72445719-754e6600-37b2-11ea-895c-b8a477fd7b5a.jpg)![image](https://user-images.githubusercontent.com/14091307/72445750-85fedc00-37b2-11ea-8a04-d7b76fb2f213.jpg) (Varys is the app with the incorrect badge in the before screenshot)

**Comment by swing7wing** [comment]
A pretty minor issue.
PS: thanks for the tweak and the open-source!

**Comment by ConorTheDev** [comment]
Will be fixed in v2
